spring.application.name=SmartSupply-Backend-Prod

spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver

# ? USAR VARIABLES
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}

ml.api.url=${ML_API_URL}